.runner: &runner
  image: registry.qnap.me/gitlab/docker-runner:latest
  tags:
    - docker
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD registry.qnap.me

stages:
  - build

build:qpkg:
  stage: build
  <<: *runner
  image:
    name: registry.qnap.me/qnap/qpkg-builder:latest
    entrypoint: [""]
  variables:
    TZ: Asia/Taipei
    BUILD_NUMBER: $CI_PIPELINE_IID
    DATA_DIR: $CI_PROJECT_DIR
    QNAP_CODESIGNING_TOKEN: bbc3888404954c228122cf4f580ba53b
  script:
    - rsync -a --exclude='data' --exclude='.cache' ./ /build
    - make -C /build 2>&1 | ts
  artifacts:
    name: "pgsql-$CI_COMMIT_REF_NAME-$CI_PIPELINE_IID"
    paths:
      - "*.qpkg"
    expire_in: '1 week'
